version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/www/aws-auto-deploy-try
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 6000
      runas: root
  AfterInstall:
    - location: scripts/install_os_dependencies.sh
      timeout: 6000
      runas: root
    - location: scripts/install_python_dependencies.sh
      timeout: 6000
      runas: root
    - location: scripts/migrate.sh
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 6000
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 6000
      runas: root