version:0.0
os: linux
hooks:
    AfterInstall:
      - location: scripts/install_os_dependencies.sh
        runas: root
      - location: scripts/install_python_dependencies.sh
        runas: root
      - location: scripts/migrate.sh
        runas: root
        runas: root
    ApplicationStart:
      - location: scripts/start_application.sh
        runas: root
    ApplicationStop:
      - location: scripts/stop_application.sh
        runas: root